# Generated by Django 4.2 on 2024-12-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_member_image_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='caption',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
